{
  "bug_id": "api-get-api-proxy-image-1761193315723",
  "workflow_id": "api-get-api-proxy-image",
  "category": "api_endpoint_error",
  "priority": 65,
  "evidence": {
    "workflow_id": "api-get-api-proxy-image",
    "started_at": "2025-10-23T04:21:55.721Z",
    "steps": [],
    "requests": [],
    "responses": [],
    "failed_at": "2025-10-23T04:21:55.723Z",
    "duration_ms": 2,
    "error": "request to http://localhost:3002/api/proxy-image failed, reason: "
  },
  "discovered_at": "2025-10-23T05:46:27.421Z"
}